### PR TITLE
Switch to Github Actions

### PR DESCRIPTION
**Pull request by petergoldstein**

### CODE REVIEW

**Comment by petergoldstein** [comment]
@ktheory I know this repo hasn't had an update in some time - since 2017.  Is this something you're still actively maintaining?

As the Dalli maintainer I'd like to ensure this gem is available and compatible with modern usage of Dalli.  Please let me know if there's any way in which I can assist.  Thanks!

**Comment by ktheory** [comment]
@petergoldstein hello, and thanks for the ping.

I am no longer using this gem in my daily work, so it hasn't gotten much attention. Would you like to maintain it?

**Comment by petergoldstein** [comment]
@ktheory Sure, I could be a (the) maintainer for this gem if you think that's the best path forward.  Would make sense since I'm maintaining Dalli itself.

If you want to add me on the repo and on Rubygems I can triage open issues and get an update out in the next week or so.

**Comment by ktheory** [comment]
>  add me on the repo and on Rubygems

Done and done! Godspeed, @petergoldstein.

**Comment by petergoldstein** [comment]
Thanks @ktheory .  Really appreciate the work on this to date and I'll take care with it going forward.

**Pull request merged**
