### PR TITLE
Always use host name instead of private elasticache IPs as internal I…

### PR DESCRIPTION
**Pull request by girak**
…Ps can change after a node is rebooted

### CODE REVIEW

**Comment by girak** [comment]
@ktheory Dalli / Rails cache should reference to the hostnames, instead of referring the ec2 internal ip.  the app can only failover correctly during the node change iff it's referenced to as a hostname.

Please consider merging this in and cut a new gem release

**Comment by readysetawesome** [comment]
+1 this is a problem for us as well.

**Comment by terencetung** [comment]
:+1: totally need this

**Comment by weeyum** [comment]
:+1:

**Comment by jldbasa** [comment]
:+1:

**Comment by ktheory** [comment]
Ping @zmillman. What do you think?

**Comment by zmillman** [comment]
Sounds good to me! I was always concerned about having to reboot the app servers to refresh IPs in the case of server reboots...but I also hadn't done anything about it since all my uptime anxiety has been focused on RDS.

**Comment by girak** [comment]
@ktheory @zmillman Thanks guys, we have just been hit again with some of the services not using the beta gem that uses this PR.  It will be great to make it official asap.

**Comment by ktheory** [comment]
@girak Thanks for this. :+1: Will publish a new gem today.

**Comment by ktheory** [comment]
Just published `v0.2.0` :smile: Thanks for your patience.

**Pull request merged**
